# ***********************************************************************
# @copyright    : Siemens AG
# @license      : GPLv3
# @author       : Andreas Kaeberlein
# @address      : Clemens-Winkler-Strasse 3, 09116 Chemnitz
#
# @maintainer   : Andreas Kaeberlein
# @telephone    : +49 371 4810-2108
# @email        : andreas.kaeberlein@siemens.com
#
# @file         : build.yml
# @date         : 2026-05-12
# @see          : https://github.com/andkae/pcimem
#
# @brief        : Build
#
# **********************************************************************/


name: Build

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'README.md'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0            # allow fetch tags, needed by 'git describe'
      - name: OS Version
        run: cat /etc/os-release
      - name: Build
        run: |
          make
